version: "3.9"
services:
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: "redis:6.0.10-alpine3.13"
    domainname: redis